# Generated by Django 6.0.1 on 2026-01-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingplan',
            name='place',
        ),
        migrations.RemoveField(
            model_name='marketingplan',
            name='promotion',
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='political',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='generated_strategy',
            field=models.TextField(default='old plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='threats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingplan',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
