# Generated by Django 6.0.1 on 2026-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_marketingplan_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingplan',
            old_name='political',
            new_name='competitors',
        ),
        migrations.RenameField(
            model_name='marketingplan',
            old_name='price',
            new_name='marketing_mix_4c',
        ),
        migrations.RenameField(
            model_name='marketingplan',
            old_name='product',
            new_name='marketing_mix_4p',
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='pestel_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
