# Generated by Django 6.0.1 on 2026-01-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_political_marketingplan_competitors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingplan',
            name='competitors',
        ),
    ]
